blank_issues_enabled: false
contact_links:
  - name: 💬 DappDriver Community Support and Questions
    url: https://github.com/assert-equals/DappDriver/discussions
    about: Ask questions and discuss with other community members
